/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weiqi_modulebase_util_KeyUtil */

#ifndef _Included_com_weiqi_modulebase_util_KeyUtil
#define _Included_com_weiqi_modulebase_util_KeyUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weiqi_modulebase_util_KeyUtil
 * Method:    getAlipayKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_weiqi_modulebase_util_KeyUtil_getAlipayKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
